name: PR Status

on:
  pull_request:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Hello
      run: echo 'Hello world'
